services:
  app-ibk-weather-v1:
    image: eclipse-temurin:17-jdk
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-ibk-weather-v1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - OPENWEATHER_API_KEY=524a1799445ad793e2b9e95c09eeb810
  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "--requirepass", "123456789"]
