apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: app-ibk-weather-v1
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s