apiVersion: v1
kind: Pod
metadata:
  name: redis-client
  labels:
    app: redis-client
spec:
  containers:
    - name: redis-client
      image: redis:7
      command: ["sleep", "infinity"]   # mantiene el pod corriendo