apiVersion: v1
kind: Service
metadata:
  name: app-ibk-weather-v1
spec:
  selector:
    app: app-ibk-weather-v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer