apiVersion: v1
kind: Service
metadata:
  name: app-ibk-weather-v1
  labels:
    app: app-ibk-weather-v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: app-ibk-weather-v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer